### ISSUE TITLE
Enhancement to Piping macros used in question editor

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-QuestionEditor#79]
It will be good if the macros are not case sensitive.

For e.g {^title} does not work but {^Title} provides value
{^Firstname} does not work but {^firstname} works

**Comment by onepointpb** [comment]
Macros are not case sensitive. And it is working in both Staging and Live.
But there are few issues in staging server only not in live. Those are:
{^title} is giving 1 instead of exact title. Please refer #78.
{^mobilenumber} is giving mobile number without country code.
{^registration} is not working.

May be the staging server is missing something. @dougmorris : Do we have to update any package in the runtime that is related to this one in staging?

**Comment by dougmorris** [comment]
@onepointpb thanks for the clarification - will look into this.

**Comment by dougmorris** [comment]
@onepointpb staging has been updated to the same as the live version.

**Comment by onepointpb** [comment]
Thank you @dougmorris . Now, it is working in staging.
